### PR TITLE
Move ruleset out of src/

### PR DESCRIPTION
**Pull request by szepeviktor**
## Description

Move ruleset to `/Ramsey`.

## Motivation and context

Every PHPCS ruleset I've seen/written uses one directory in the root.
That is all.

### CODE REVIEW

**Comment by szepeviktor** [comment]
There is a brand new action:
```yaml
          - name: "Validate ruleset"
            uses: "szepeviktor/phpcs-ruleset-validator@v0.1.0"
            with:
                xml_ruleset: "Ramsey/ruleset.xml"
```

**Comment by ramsey** [comment]
I’ll have to give some thought to this change. It doesn’t follow the standard code pattern of any of my other repositories, nor does it follow the [pds/skeleton](https://github.com/php-pds/skeleton/tree/1.0.0) standard I try to follow.

I like the new action. Does that mean I can remove the xmllint scripts?

**Comment by szepeviktor** [comment]
There could be a misunderstanding.

> pds/skeleton
> 
> This publication describes a standard filesystem skeleton suitable for all PHP packages.

This is a PHPCS standard. PHPCS is an extremely rare animal. Please look at the standards this standard uses. All of them are without `src/`.

**Comment by szepeviktor** [comment]
> I like the new action. Does that mean I can remove the xmllint scripts?

Thank you.
This is up to you. In turn I like your PHP code checking XML.

**Comment by ramsey** [comment]
> This is a PHPCS standard.

Does PHPCS document this directory structure as the preferred structure, or is it a matter of convention? PHPCS goes way back to the PEAR days, so it retains some of the older ways of organizing PHP code. 🙂

**Comment by szepeviktor** [comment]
I do not know.

BTW PHPCS is not a standard, it does use `src/`
https://github.com/squizlabs/PHP_CodeSniffer/tree/master/src

**Comment by szepeviktor** [comment]
- all of these https://github.com/PHPCSStandards
- https://github.com/slevomat/coding-standard too

**Comment by ramsey** [comment]
That works for me. I merged the other PR, so you might want to rebase this one and change the path in the workflow.

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by ramsey** [comment]
Thank you!

**Comment by szepeviktor** [comment]
You're welcome.

It was a pleasure to work on this ruleset.

**Pull request merged**
